In [ ]:
from collections import deque


In [ ]:
def bfs(graph, start):
    visited = set()
    queue = deque([start])
    visited.add(start)

    while queue:
        vertex = queue.popleft()
        print(vertex, end=' ')

        for neighbor in graph[vertex]:
            if neighbor not in visited:
                queue.append(neighbor)
                visited.add(neighbor)


In [ ]:
graph={
    0:[1, 3],
    1:[0, 2, 3],
    2:[1, 4, 5],
    3:[0, 1, 4],
    4:[2, 3, 5],
    5:[2, 4]
}


In [ ]:


start_vertex = 0
print("BFS traversal starting from vertex", start_vertex)
bfs(graph, start_vertex)



BFS traversal starting from vertex 0
0 1 3 2 4 5 

In [31]:
#definition

def dfs2(graph, start):
    visited = set()
    stack = [start]

    while stack:
        vertex = stack.pop()

        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)

            stack.extend(neighbor for neighbor in graph[vertex] if neighbor not in visited)

In [32]:
graph = {
    'A': ['B', 'S'],
    'B': ['A'],
    'C': ['D', 'E', 'F', 'S'],
    'D': ['C'],
    'E': ['C', 'H'],
    'F': ['C', 'G'],
    'G': ['F', 'H', 'S'],
    'H': ['E', 'G'],
    'S': ['A', 'C', 'G']
}

In [34]:
# Starting vertex and applying DFS with the second implementation
start_vertex='A'
print("DFS traversal starting from vertex", start_vertex, ":")
dfs2(graph, start_vertex)



DFS traversal starting from vertex A :
A S G H E C F D B 

In [35]:
import numpy as np

# Define the initial and final states
initial_state = np.array([[2, 8, 3],
                          [1, 6, 4],
                          [7, 0, 5]])

final_state = np.array([[1, 2, 3],
                        [8, 0, 4],
                        [7, 6, 5]])


In [36]:
# Define the heuristic function
def heuristic(state):
    # A simple heuristic: count the number of misplaced tiles
    return np.sum(state != final_state)


In [37]:
# Call the A* algorithm with the initial and final states
result=astar(initial_state, final_state, heuristic)
# Print the result
if result is not None:
    print("Final State:")
    print(result)
else:
    print("A* algorithm did not find a solution.")

Final State:
[[1 2 3]
 [8 0 4]
 [7 6 5]]
